// Code generated by Prismic. DO NOT EDIT.

import CommunityFeature from "./CommunityFeature/index.svelte";
import ContentWidth from "./ContentWidth/index.svelte";
import Hero from "./Hero/index.svelte";
import HomeHero from "./HomeHero/index.svelte";
import IconGrid from "./IconGrid/index.svelte";
import ImageAndText from "./ImageAndText/index.svelte";
import ImageBanner from "./ImageBanner/index.svelte";
import RichText from "./RichText/index.svelte";
import ThreeStepPlan from "./ThreeStepPlan/index.svelte";

export const components = {
	community_feature: CommunityFeature,
	content_width_media: ContentWidth,
	hero: Hero,
	home_hero: HomeHero,
	icon_grid: IconGrid,
	image_and_text: ImageAndText,
	image_banner: ImageBanner,
	rich_text: RichText,
	three_step_plan: ThreeStepPlan
};